# Generated by Django 3.0.6 on 2020-07-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_quizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='percentscore',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
